/**
 * The region harness `genRegion` (SP3a spec §6.1): generates a w × h region of columns up to the provisional T
 * stage, in a chosen order, on 1 thread (a plain `ArrayBuffer` store, `fillColumnT` in process) or on 4
 * `worker_threads` (a growable `SharedArrayBuffer` store; each worker runs `regionWorker.ts`, and the main thread
 * hands the next column of the list to whichever worker is idle, so every column is written by exactly one thread),
 * optionally through the region cache (`cache.ts`). The result is read through a `RegionView`, which reads the
 * store per column and never stitches the region into one array.
 */
import { performance } from 'node:perf_hooks';
import { Worker } from 'node:worker_threads';
import { hex64 } from '../../src/core/hash';
import type { Params } from '../../src/core/params/schema';
import { Xoshiro128 } from '../../src/core/rng';
import { seedFromInput } from '../../src/core/seed';
import { genKey, stageHashes } from '../../src/core/stage/hash';
import { createGenContext } from '../../src/gen/context';
import { fillColumnT, regionHash } from '../../src/metrics/region';
import { protoAt } from '../../src/world/store/columnTable';
import { createStore, type ColumnView, type VoxelStore } from '../../src/world/store/store';
import { readRegionDump, regionCachePath, srcKey, writeRegionDump, type RegionCacheHeader, type RegionUpTo } from './cache';
import { buildNodeTaskWorker } from './nodeWorker';
import type { RegionAttachMsg, RegionColumnMsg, RegionWorkerReply } from './regionWorker';

export type RegionOrder = 'spiral' | 'shuffled';

export interface GenRegionOptions {
  /** World seed text, as typed in the UI ('42'). */
  readonly seed: string;
  readonly params: Params;
  readonly cx0: number;
  readonly cz0: number;
  /** 1 … 64 columns per side (a larger region would collide on the 64 × 64 torus). */
  readonly w: number;
  readonly h: number;
  readonly upTo: RegionUpTo;
  readonly order: RegionOrder;
  readonly threads: 1 | 4;
  /** Read the dump on a hit, write it on a miss (default false: never touch a dump). */
  readonly cache?: boolean;
  /** Seed of the `shuffled` permutation (default 1). */
  readonly shuffleSeed?: number;
  /** Test seam: the directory of the dumps (default `test/.cache/regions/`). */
  readonly cacheDir?: string;
  /** Test seam: the source key to use instead of the repository's (`srcKey()`). */
  readonly srcKey?: RegionCacheHeader['srcKey'];
  /** Where the 4-thread worker bundle is built, under test/.cache/ (default `regionWorker`; one per test file). */
  readonly workerDir?: string;
}

/** Proto data of a generated region, read through the store. x, z are world block coordinates inside the region. */
export interface RegionView {
  readonly store: VoxelStore;
  readonly cx0: number;
  readonly cz0: number;
  readonly w: number;
  readonly h: number;
  block(x: number, y: number, z: number): number;
  fluid(x: number, y: number, z: number): number;
  /** The zoomed surface biome (aux A `surfaceBiome`). */
  biome(x: number, z: number): number;
  worldSurfaceWG(x: number, z: number): number;
  oceanFloorWG(x: number, z: number): number;
  /** A copy of column (cx, cz)'s 24 proto descriptors: blocks then fluid per section (slot id, or −1 − value). */
  descriptors(cx: number, cz: number): Int32Array;
  /** hex64 of `regionHash` over the region, or over a sub-window of it. */
  hash(cx0?: number, cz0?: number, w?: number, h?: number): string;
}

export interface RegionResult {
  readonly view: RegionView;
  /** `perColumnMs` is indexed row-major in the region, `(cz − cz0)·w + (cx − cx0)`; on a hit it holds the rebuild. */
  readonly timings: { readonly perColumnMs: Float64Array; readonly totalMs: number };
  readonly cacheHit: boolean;
  /** Columns generated by each thread (one entry per thread; `[0]` on a cache hit). */
  readonly columnsPerThread: number[];
}

function checkSize(what: string, w: number, h: number): void {
  for (const [name, v] of [['w', w], ['h', h]] as const) {
    if (!Number.isInteger(v) || v < 1 || v > 64) throw new RangeError(`${what}: ${name} = ${v} outside 1 … 64`);
  }
}

/**
 * The column list (§6.1). `spiral`: the centre (cx0 + ⌊w/2⌋, cz0 + ⌊h/2⌋), then square rings of growing radius r,
 * each walked clockwise seen from +y from its north-west corner (cx − r, cz − r): east along the north edge, south
 * along the east edge, west along the south edge, north along the west edge; columns outside the region are
 * skipped. `shuffled`: a Fisher-Yates permutation of the row-major list (cz outer), i from n − 1 down to 1 swapping
 * with j = `nextInt(i + 1)` of `Xoshiro128(shuffleSeed)`.
 */
export function regionColumns(order: RegionOrder, cx0: number, cz0: number, w: number, h: number, shuffleSeed = 1): Array<[number, number]> {
  checkSize('regionColumns', w, h);
  const out: Array<[number, number]> = [];
  if (order === 'shuffled') {
    for (let cz = cz0; cz < cz0 + h; cz++) for (let cx = cx0; cx < cx0 + w; cx++) out.push([cx, cz]);
    const rng = new Xoshiro128(shuffleSeed);
    for (let i = out.length - 1; i > 0; i--) {
      const j = rng.nextInt(i + 1);
      [out[i], out[j]] = [out[j]!, out[i]!];
    }
    return out;
  }
  if (order !== 'spiral') throw new Error(`regionColumns: unknown order '${String(order)}'`);
  const cx = cx0 + Math.floor(w / 2);
  const cz = cz0 + Math.floor(h / 2);
  const inside = (x: number, z: number) => x >= cx0 && x < cx0 + w && z >= cz0 && z < cz0 + h;
  const add = (x: number, z: number) => {
    if (inside(x, z)) out.push([x, z]);
  };
  add(cx, cz);
  const rMax = Math.max(cx - cx0, cx0 + w - 1 - cx, cz - cz0, cz0 + h - 1 - cz);
  for (let r = 1; r <= rMax; r++) {
    for (let x = cx - r; x <= cx + r; x++) add(x, cz - r);
    for (let z = cz - r + 1; z <= cz + r; z++) add(cx + r, z);
    for (let x = cx + r - 1; x >= cx - r; x--) add(x, cz + r);
    for (let z = cz + r - 1; z > cz - r; z--) add(cx - r, z);
  }
  return out;
}

/** A `RegionView` over the w × h region at (cx0, cz0) of `store`; every column must hold its proto set. */
export function regionView(store: VoxelStore, cx0: number, cz0: number, w: number, h: number): RegionView {
  checkSize('regionView', w, h);
  const views: ColumnView[] = [];
  for (let cz = cz0; cz < cz0 + h; cz++) {
    for (let cx = cx0; cx < cx0 + w; cx++) {
      const v = store.proto(cx, cz);
      if (v === null) throw new Error(`regionView: column (${cx}, ${cz}) has no proto set in the store`);
      views.push(v);
    }
  }
  const columnAt = (cx: number, cz: number): number => {
    if (!Number.isInteger(cx) || !Number.isInteger(cz) || cx < cx0 || cx >= cx0 + w || cz < cz0 || cz >= cz0 + h) {
      throw new RangeError(`regionView: column (${cx}, ${cz}) outside the region`);
    }
    return (cz - cz0) * w + (cx - cx0);
  };
  const col = (x: number, z: number): ColumnView => views[columnAt(x >> 4, z >> 4)]!;
  const aux = (x: number, z: number) => {
    const a = col(x, z).aux();
    if (a === null) throw new Error(`regionView: column (${x >> 4}, ${z >> 4}) has no aux A`);
    return { a, i: ((z & 15) << 4) | (x & 15) };
  };
  return {
    store, cx0, cz0, w, h,
    block: (x, y, z) => col(x, z).block(x & 15, y, z & 15),
    fluid: (x, y, z) => col(x, z).fluid(x & 15, y, z & 15),
    biome: (x, z) => { const { a, i } = aux(x, z); return a.surfaceBiome[i]!; },
    worldSurfaceWG: (x, z) => { const { a, i } = aux(x, z); return a.worldSurfaceWG[i]!; },
    oceanFloorWG: (x, z) => { const { a, i } = aux(x, z); return a.oceanFloorWG[i]!; },
    descriptors(cx, cz) {
      columnAt(cx, cz);
      const d0 = protoAt(store.table.find(cx, cz), 0);
      return store.table.ints.slice(d0, d0 + 48);
    },
    hash(hx = cx0, hz = cz0, hw = w, hh = h) {
      checkSize('regionView.hash', hw, hh);
      columnAt(hx, hz);
      columnAt(hx + hw - 1, hz + hh - 1);
      return hex64(regionHash(store, hx, hz, hw, hh));
    },
  };
}

const sameChannel = (a: Uint16Array | Uint8Array | number, b: Uint16Array | Uint8Array | number): boolean => {
  if (typeof a === 'number' || typeof b === 'number') return a === b;
  return Buffer.from(a.buffer, a.byteOffset, a.byteLength).equals(Buffer.from(b.buffer, b.byteOffset, b.byteLength));
};

/**
 * The first difference between two views of the same region, or null when they hold the same proto data: per
 * column, each section's blocks and fluid (uniform against uniform by value, dense against dense by bytes; a
 * uniform section never equals a dense one, so the per-channel layout must match too) and the 4096 aux A bytes.
 * Byte comparison, much faster than hashing both regions.
 */
export function regionDiff(a: RegionView, b: RegionView): string | null {
  if (a.cx0 !== b.cx0 || a.cz0 !== b.cz0 || a.w !== b.w || a.h !== b.h) return 'the views cover other regions';
  for (let cz = a.cz0; cz < a.cz0 + a.h; cz++) {
    for (let cx = a.cx0; cx < a.cx0 + a.w; cx++) {
      const va = a.store.proto(cx, cz)!;
      const vb = b.store.proto(cx, cz)!;
      for (let sy = 0; sy < 24; sy++) {
        if (!sameChannel(va.sectionBlocks(sy), vb.sectionBlocks(sy))) return `column (${cx}, ${cz}) section ${sy}: blocks differ`;
        if (!sameChannel(va.sectionFluid(sy), vb.sectionFluid(sy))) return `column (${cx}, ${cz}) section ${sy}: fluid differs`;
      }
      const xa = va.aux();
      const xb = vb.aux();
      const bytes = (x: typeof xa) => (x === null ? Buffer.alloc(4096) : Buffer.from(x.worldSurfaceWG.buffer, x.worldSurfaceWG.byteOffset, 4096));
      if (!bytes(xa).equals(bytes(xb))) return `column (${cx}, ${cz}): aux A differs`;
    }
  }
  return null;
}

const workerScripts = new Map<string, Promise<string>>();

function regionWorkerScript(dir: string): Promise<string> {
  let p = workerScripts.get(dir);
  if (p === undefined) {
    p = buildNodeTaskWorker(dir, { entry: 'test/harness/regionWorker.ts' });
    workerScripts.set(dir, p);
  }
  return p;
}

/** Sends one message and waits for the worker's single reply; rejects if the worker fails or exits first. */
function ask(w: Worker, msg: RegionAttachMsg | RegionColumnMsg): Promise<RegionWorkerReply> {
  return new Promise((resolve, reject) => {
    const onError = (e: Error) => { off(); reject(e); };
    const onExit = (code: number) => { off(); reject(new Error(`region worker exited (${code})`)); };
    const onMessage = (r: RegionWorkerReply) => { off(); resolve(r); };
    const off = () => { w.off('error', onError); w.off('exit', onExit); w.off('message', onMessage); };
    w.on('error', onError);
    w.on('exit', onExit);
    w.on('message', onMessage);
    w.postMessage(msg);
  });
}

/** Generates `cols` on 4 worker threads over `store` (shared); fills `ms` (row-major) and returns columns per thread. */
async function generateThreaded(store: VoxelStore, o: GenRegionOptions, cols: ReadonlyArray<[number, number]>, ms: Float64Array): Promise<number[]> {
  const script = await regionWorkerScript(o.workerDir ?? 'regionWorker');
  const workers = Array.from({ length: 4 }, () => new Worker(script));
  const written = new Uint8Array(cols.length);
  const perThread = [0, 0, 0, 0];
  try {
    const ready = await Promise.all(workers.map((w) => ask(w, { type: 'attach', handles: store.handles(), seedText: o.seed, params: o.params })));
    for (const r of ready) if (r.type !== 'ready') throw new Error(`region worker: ${r.type === 'error' ? r.message : r.type}`);
    let next = 0;
    const drain = async (t: number): Promise<void> => {
      while (next < cols.length) {
        const [cx, cz] = cols[next++]!;
        const r = await ask(workers[t]!, { type: 'column', cx, cz });
        if (r.type !== 'done') throw new Error(`region worker ${t}, column (${cx}, ${cz}): ${r.type === 'error' ? r.message : r.type}`);
        if (r.cx !== cx || r.cz !== cz) throw new Error(`region worker ${t}: asked (${cx}, ${cz}), done (${r.cx}, ${r.cz})`);
        const k = (cz - o.cz0) * o.w + (cx - o.cx0);
        written[k]!++;
        ms[k] = r.ms;
        perThread[t]!++;
      }
    };
    await Promise.all(workers.map((_, t) => drain(t)));
  } finally {
    await Promise.all(workers.map((w) => w.terminate()));
  }
  const wrong = written.findIndex((n) => n !== 1);
  if (wrong >= 0) throw new Error(`genRegion: column ${wrong} (row-major) written ${written[wrong]} times`);
  return perThread;
}

/**
 * Generates the region (§6.1). The store is fresh per call: a plain `ArrayBuffer` one for 1 thread, a growable
 * `SharedArrayBuffer` one for 4 (and for a cache hit with `threads: 4`, rebuilt in this thread).
 */
export async function genRegion(o: GenRegionOptions): Promise<RegionResult> {
  checkSize('genRegion', o.w, o.h);
  if (o.threads !== 1 && o.threads !== 4) throw new Error(`genRegion: threads ${String(o.threads)} (1 or 4)`);
  if (o.upTo !== 'T') throw new Error(`genRegion: upTo '${String(o.upTo)}' (SP3a has 'T' only)`);
  const cols = regionColumns(o.order, o.cx0, o.cz0, o.w, o.h, o.shuffleSeed ?? 1);
  const t0 = performance.now();
  const store = createStore({ shared: o.threads === 4 });
  const header: RegionCacheHeader | null = o.cache === true
    ? {
        genKey: genKey(seedFromInput(o.seed), stageHashes(o.params)), srcKey: o.srcKey ?? srcKey(),
        cx0: o.cx0, cz0: o.cz0, w: o.w, h: o.h, upTo: o.upTo,
      }
    : null;
  const path = header === null ? '' : regionCachePath(header, o.cacheDir);
  if (header !== null) {
    const ms = readRegionDump(store, header, path);
    if (ms !== null) {
      return {
        view: regionView(store, o.cx0, o.cz0, o.w, o.h), timings: { perColumnMs: ms, totalMs: performance.now() - t0 },
        cacheHit: true, columnsPerThread: [0],
      };
    }
  }
  const ms = new Float64Array(o.w * o.h);
  let columnsPerThread: number[];
  if (o.threads === 1) {
    const ctx = createGenContext(seedFromInput(o.seed), o.params);
    const never = () => false;
    for (const [cx, cz] of cols) {
      const c0 = performance.now();
      fillColumnT(store, ctx, cx, cz, never);
      ms[(cz - o.cz0) * o.w + (cx - o.cx0)] = performance.now() - c0;
    }
    columnsPerThread = [cols.length];
  } else {
    columnsPerThread = await generateThreaded(store, o, cols, ms);
  }
  if (header !== null) writeRegionDump(store, header, path);
  return {
    view: regionView(store, o.cx0, o.cz0, o.w, o.h), timings: { perColumnMs: ms, totalMs: performance.now() - t0 },
    cacheHit: false, columnsPerThread,
  };
}
