/**
 * The slice job (SP3a spec §5.1): the voxels of the vertical slice under a line, from a worker-local voxel store.
 * Sample (i, y) is the proto voxel (⌊xᵢ⌋, y, ⌊zᵢ⌋), where (xᵢ, zᵢ) = `segmentPointAt(segment, i)`, for i 0 … 511 and
 * y −64 … 319. A run covers a range [from, to) of the samples (SP3b spec §6: the pool gives each worker one range;
 * the default is the whole line) and writes sample (i, y) at `slicePartIndex(i, y, from, to)` (row 0 is y 319; for
 * the whole line that is `sliceIndex(i, y)`). Only the columns of the range's samples are generated, so a column two
 * ranges share is generated by both workers.
 *
 * The store (an `ArrayBuffer` store of 32 MiB of blocks and 16 MiB of bytes) is created on the first run and kept;
 * an LRU keyed by colKey holds at most 64 generated columns of one epoch. The job walks the samples in order: a
 * straight segment enters each column once (⌊x⌋ and ⌊z⌋ are monotone along it), so a column's samples are
 * contiguous. On reaching a new column it calls `stop`, then takes the column from the LRU or, on a miss, frees the
 * resident column on the same torus record (if any), frees the least recently used column if 64 are resident and
 * runs `fillColumnT` with `stop` and the job's epoch. It reads all of the column's samples before moving on, so it
 * never holds two columns of one torus record and `claimColumn` never throws `SlotBusy`. A stopped column is freed
 * by `fillColumnT` and not inserted; the run returns null.
 */
import { colKey, torusSlot } from '../core/coords';
import type { GenContext } from '../gen/context';
import { segmentPointAt, segmentProblem, type Segment } from '../metrics/crossSection';
import { fillColumnT } from '../metrics/region';
import { createStore, type VoxelStore } from '../world/store/store';
import { SLICE_POINTS, SLICE_ROWS, sliceRangeProblem } from './protocol';

const COL_KEY = colKey;
const TORUS = torusSlot;
const POINT_AT = segmentPointAt;
const PROBLEM = segmentProblem;
const FILL = fillColumnT;
const CREATE_STORE = createStore;
const N = SLICE_POINTS;
const ROWS = SLICE_ROWS;
const RANGE_PROBLEM = sliceRangeProblem;

const MiB = 1 << 20;
/**
 * The slice store's pool maxima: 65 proto columns need at most 65 × 24 = 1,560 block slots and 65 × 26 = 1,690 byte
 * slots (24 fluid sections, aux A and aux B; SP3a §5.1, SP3b §6), within the 4,096 slots of each.
 */
export const SLICE_MAX_BLOCK_BYTES = 32 * MiB;
export const SLICE_MAX_BYTE_BYTES = 16 * MiB;
/** Columns the slice store keeps between jobs. */
export const SLICE_LRU_COLUMNS = 64;

/**
 * The voxels of samples [from, to) of a slice: (to − from)·SLICE_ROWS block states and fluid bytes, sample (i, y) at
 * `slicePartIndex(i, y, from, to)` (`sliceIndex(i, y)` for the whole line).
 */
export interface SliceData {
  readonly blocks: Uint16Array<ArrayBuffer>;
  readonly fluid: Uint8Array<ArrayBuffer>;
}

export interface SliceJob {
  /**
   * Samples [from, to) (default the whole line) of the slice under `segment`, with columns generated by `ctx` and
   * claimed with `epoch`; null when `stop` fired. A run of another epoch than the resident columns' first frees them.
   * Throws RangeError on a segment with a problem (`segmentProblem`: an end outside the window, or A = B) or a range
   * that is not integers with 0 ≤ from < to ≤ 512 (`sliceRangeProblem`).
   */
  run(ctx: GenContext, epoch: number, segment: Segment, stop: () => boolean, from?: number, to?: number): SliceData | null;
  /** Frees every resident column and empties the LRU (a configure). */
  reset(): void;
  /** The slice store, null before the first run. */
  readonly store: VoxelStore | null;
  /** The resident columns (cx, cz), least recently used first. */
  resident(): Array<[number, number]>;
  /** Columns generated (LRU misses that completed) and taken from the LRU, over the job's lifetime. */
  readonly misses: number;
  readonly hits: number;
}

interface Resident {
  readonly cx: number;
  readonly cz: number;
}

export function createSliceJob(): SliceJob {
  let store: VoxelStore | null = null;
  /** Insertion order = recency: a hit is deleted and set again. */
  const lru = new Map<number, Resident>();
  /** colKey of the resident column on each used torus record. */
  const bySlot = new Map<number, number>();
  let lruEpoch: number | null = null;
  let misses = 0;
  let hits = 0;
  /** The current column's 24 proto block and fluid sections (a dense view or the uniform value). */
  const secBlocks: Array<Uint16Array | number> = new Array<Uint16Array | number>(24).fill(0);
  const secFluid: Array<Uint8Array | number> = new Array<Uint8Array | number>(24).fill(0);

  const drop = (st: VoxelStore, key: number): void => {
    const c = lru.get(key)!;
    st.freeColumn(c.cx, c.cz);
    lru.delete(key);
    bySlot.delete(TORUS(c.cx, c.cz));
  };

  const reset = (): void => {
    if (store !== null) for (const key of [...lru.keys()]) drop(store, key);
    lru.clear();
    bySlot.clear();
    lruEpoch = null;
  };

  /** Loads column (cx, cz) into the section arrays from the LRU or by generating it; false when stopped. */
  const load = (st: VoxelStore, ctx: GenContext, cx: number, cz: number, epoch: number, stop: () => boolean): boolean => {
    const key = COL_KEY(cx, cz);
    const hit = lru.get(key);
    if (hit !== undefined) {
      lru.delete(key);
      lru.set(key, hit);
      hits++;
    } else {
      const slot = TORUS(cx, cz);
      const holder = bySlot.get(slot);
      if (holder !== undefined) drop(st, holder);
      if (lru.size >= SLICE_LRU_COLUMNS) drop(st, lru.keys().next().value!);
      if (!FILL(st, ctx, cx, cz, stop, epoch)) return false;
      lru.set(key, { cx, cz });
      bySlot.set(slot, key);
      misses++;
    }
    const v = st.proto(cx, cz);
    if (v === null) throw new Error(`slice: column (${cx}, ${cz}) is resident but has no proto set`);
    for (let sy = 0; sy < 24; sy++) {
      secBlocks[sy] = v.sectionBlocks(sy);
      secFluid[sy] = v.sectionFluid(sy);
    }
    return true;
  };

  return {
    get store() { return store; },
    get misses() { return misses; },
    get hits() { return hits; },
    resident: () => [...lru.values()].map((c): [number, number] => [c.cx, c.cz]),
    reset,
    run(ctx, epoch, segment, stop, from = 0, to = N) {
      const problem = PROBLEM(segment) ?? RANGE_PROBLEM(from, to);
      if (problem !== null) throw new RangeError(`slice: ${problem}`);
      if (lruEpoch !== epoch) {
        reset();
        lruEpoch = epoch;
      }
      const st = store ??= CREATE_STORE({ shared: false, maxBlockBytes: SLICE_MAX_BLOCK_BYTES, maxByteBytes: SLICE_MAX_BYTE_BYTES });
      const w = to - from;
      const blocks = new Uint16Array(w * ROWS);
      const fluid = new Uint8Array(w * ROWS);
      let curCx = 0;
      let curCz = 0;
      let loaded = false;
      for (let i = from; i < to; i++) {
        const [x, z] = POINT_AT(segment, i);
        const bx = Math.floor(x);
        const bz = Math.floor(z);
        const cx = bx >> 4;
        const cz = bz >> 4;
        if (!loaded || cx !== curCx || cz !== curCz) {
          if (stop() || !load(st, ctx, cx, cz, epoch, stop)) return null;
          curCx = cx;
          curCz = cz;
          loaded = true;
        }
        const inSection = ((bz & 15) << 4) | (bx & 15);
        // Row of y = 16·sy − 64 + ly is 319 − y = 383 − 16·sy − ly; the part's rows are w samples wide.
        for (let sy = 0; sy < 24; sy++) {
          const b = secBlocks[sy]!;
          const f = secFluid[sy]!;
          let at = (383 - 16 * sy) * w + (i - from);
          for (let ly = 0; ly < 16; ly++, at -= w) {
            blocks[at] = typeof b === 'number' ? b : b[(ly << 8) | inSection]!;
            fluid[at] = typeof f === 'number' ? f : f[(ly << 8) | inSection]!;
          }
        }
      }
      return { blocks, fluid };
    },
  };
}
